<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <style>

    </style>
</head>
<body>

<input type="text">
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.26.0/babel.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/babel">
    let _timer = null;
    let _timeoutErr = null;
    const myFetch = async(url, options, ctrlOptions) => {
        if (Window.prototype.TimeoutError === undefined) {
            function TimeoutError(msg){ this.message = msg;}
            TimeoutError.prototype = new Error();  // because in ES6, the check instanceof for subclass of builtins class like Array, Error,... is no longer suppoted, 
            // so we need to use legacy way: prototype chain
            Window.prototype.TimeoutError = TimeoutError;
        }
        if (Window.prototype.RetryExpireError === undefined) {
            function RetryExpireError(msg){ this.message = msg;}
            RetryExpireError.prototype = new Error();
            Window.prototype.RetryExpireError = RetryExpireError;
        }
        return new Promise((resolve, reject) => {
            if (ctrlOptions && typeof ctrlOptions.timeout === "number") {
                if (! _timer) {
                    _timer = setTimeout(() => {
                        const err = new TimeoutError();
                        console.log("timeout up here");
                        reject(err);
                    }, ctrlOptions.timeout);
                }
            }
            const retry = ctrlOptions && ctrlOptions.retry;
            if (typeof retry === "number" && retry > 0) {
                fetch(url, options).then(res => {
                    if (! res.ok) {
                        if (_timeoutErr) {
                            console.log("got here1");
                            throw _timeoutErr;
                        } else {
                            const o = {...options, ...{retry: options.retry - 1}};
                            
                        }
                    } else {
                        resolve(res);
                    }
                }).catch(err => {
                    if (err instanceof RetryError) {
                        const o = {...options, ...{retry: options.retry - 1}};
                        // if (o.retry === 0) {
                        //     console.log("here")
                        //     reject(err);
                        //     if (_timer) {
                        //         clearTimeout(_timer);
                        //         _timer = null;
                        //     }
                        // } else {
                            myFetch(url, o);
                        // }
                    } else {
                        console.log("got here2");
                        reject(_timeoutErr);
                    }
                });

            }

        });
    };
</script>
<script type="text/babel">
    let _timer = null;
    const myFetch = async(url, options) => {
        if (Window.prototype.TimeoutError === undefined) {
            function TimeoutError(){}
            TimeoutError.prototype = new Error();  // because in ES6, the check instanceof for subclass of builtins class like Array, Error,... is no longer suppoted, 
            // so we need to use legacy way: prototype chain
            Window.prototype.TimeoutError = TimeoutError;
        }
        if (Window.prototype.RetryError === undefined) {
            function RetryError(){}
            RetryError.prototype = new Error();
            Window.prototype.RetryError = RetryError;
        }
        return new Promise((resolve, reject) => {
            let _timeoutErr = null;
            const getTimeoutErr = () => _timeoutErr;
            if(options && typeof options.timeout === "number") {
                // if (_timer) {
                //     clearTimeout(_timer);
                //     _timer = null;
                // }
                // _timer = setTimeout(() => {
                //     const err = new TimeoutError();
                //     console.log("timeout up here")
                //     _timeoutErr = err;
                //     reject(err);
                // }, options.timeout);
                if (! _timer) {
                    _timer = setTimeout(() => {
                        const err = new TimeoutError();
                        console.log("timeout up here")
                        _timeoutErr = err;
                        reject(err);
                    }, options.timeout);
                }
            }
            const retry = options && options.retry;
            if (typeof retry === "number" && retry > 0) {
                fetch(url, options).then(res => {
                    if (! res.ok) {
                        if (_timeoutErr) {
                            console.log("got here1");
                            throw _timeoutErr;
                        } else {
                            throw new RetryError();
                        }
                    } else {
                        resolve(res);
                    }
                }).catch(err => {
                    if (err instanceof RetryError) {
                        const o = {...options, ...{retry: options.retry - 1}};
                        // if (o.retry === 0) {
                        //     console.log("here")
                        //     reject(err);
                        //     if (_timer) {
                        //         clearTimeout(_timer);
                        //         _timer = null;
                        //     }
                        // } else {
                            myFetch(url, o);
                        // }
                    } else {
                        console.log("got here2");
                        reject(_timeoutErr);
                    }
                });
            } else if (typeof retry === "number"){
                console.log("here");
                if (_timer) {
                    clearTimeout(_timer);
                    _timer = null;
                }
                reject(new Error("retry expired"));
            } else {
                fetch(url, options).then(res => resolve(res));
            }
            // fetch(url, options).then(res => resolve(res));
        });
    }

    const url = "http://localhost:3000/delay";
    myFetch(url, {retry: 3, timeout: 7000}).then(res => {
        if (res.ok) {
            return res.text();
        } else if (res instanceof TimeoutError){
            throw res;
        } else {
            throw new Error(res.status);
        }
    }).then(text => console.log(text)).catch(err => {
        if (err instanceof TimeoutError) {
            console.log("oops, you are timed out");
        } else if (err instanceof RetryError) {
            console.log(err.message);
        } else if (err.message === "404"){
            console.log("Not Found");
        } else {
            console.log(`${err.name}: ${err.message}`);
        }
    });

</script>
</body>
</html>